version: '3'
services:
    db-server:
      image: mcr.microsoft.com/mssql/server:2017-CU12-ubuntu
      environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=Iura2323!!
        - MSSQL_TCP_PORT=1433
      ports:
        - "1433:1433"

      volumes:
        - /User/iura/Documents/code/docker:/var/lib/mssql